language: go
sudo: false

go:
- 1.8.x
- master

matrix:
  allow_failures:
    - go: tip

script:
- go vet ./...

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
